/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrentalsystem;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author user
 */
public class Form_Car extends javax.swing.JFrame {

    /**
     * Creates new form Form_Car
     */
    Car cr = new Car();
    brand_cls brand = new brand_cls();
   HashMap<Integer,String> map =brand.brandsHashMap();
    public Form_Car() {
        initComponents();
        this.setLocationRelativeTo(null);
        ButtonGroup btn_group = new ButtonGroup();
        
        btn_group.add(jRadioButton_Automatic);
        btn_group.add(jRadioButton_Manual);
         populateComboboxBrands();
    }
   //function to populate jcombobrand box
    public void populateComboboxBrands()
    {
        
        for(String s:map.values())
        {
            jComboBox_brand.addItem(s);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox_AC = new javax.swing.JCheckBox();
        jCheckBox_AB = new javax.swing.JCheckBox();
        jCheckBox_HS = new javax.swing.JCheckBox();
        jCheckBox_SR = new javax.swing.JCheckBox();
        jCheckBox_Bluetooth = new javax.swing.JCheckBox();
        jCheckBox_NS = new javax.swing.JCheckBox();
        jCheckBox_GPS = new javax.swing.JCheckBox();
        jCheckBox_EW = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Model = new javax.swing.JTextField();
        jComboBox2_Fuel = new javax.swing.JComboBox<>();
        jComboBox_brand = new javax.swing.JComboBox<>();
        jComboBox_color = new javax.swing.JComboBox<>();
        int max = 20;
        int min=2;
        int step =1;
        int i = 2;

        SpinnerModel spinner_model = new SpinnerNumberModel(i,min,max,step);
        jSpinner_Passenger = new javax.swing.JSpinner(spinner_model);
        jTextField_Class = new javax.swing.JTextField();
        jButton_Add = new javax.swing.JButton();
        jButton_Brands_List_ = new javax.swing.JButton();
        jButton_Add_Images_ = new javax.swing.JButton();
        jRadioButton_Automatic = new javax.swing.JRadioButton();
        jRadioButton_Manual = new javax.swing.JRadioButton();
        jButton_Reset = new javax.swing.JButton();
        jLabel_id = new javax.swing.JLabel();
        jSpinner_id = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jButton_Add1 = new javax.swing.JButton();
        jButton_Add2 = new javax.swing.JButton();
        jButton_Brands_List_1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(29, 209, 161));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CARS");

        jButton1.setText("Back To Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jLabel5))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Passengers:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("FEATURES:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("  Brand:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("  Price Per Day:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("  Model:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Colour:");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("GearBox:");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("  Fuel:");

        jCheckBox_AC.setText("Air Conditioning");
        jCheckBox_AC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ACActionPerformed(evt);
            }
        });

        jCheckBox_AB.setText("Air Bags");
        jCheckBox_AB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_ABActionPerformed(evt);
            }
        });

        jCheckBox_HS.setText("Heated Seats");
        jCheckBox_HS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_HSActionPerformed(evt);
            }
        });

        jCheckBox_SR.setText("Sun roof");
        jCheckBox_SR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_SRActionPerformed(evt);
            }
        });

        jCheckBox_Bluetooth.setText("Bluetooth");
        jCheckBox_Bluetooth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_BluetoothActionPerformed(evt);
            }
        });

        jCheckBox_NS.setText("Navigation Systems");
        jCheckBox_NS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_NSActionPerformed(evt);
            }
        });

        jCheckBox_GPS.setText("GPS");
        jCheckBox_GPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_GPSActionPerformed(evt);
            }
        });

        jCheckBox_EW.setText("Electric windows");
        jCheckBox_EW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_EWActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox_AC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox_AB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(72, 72, 72)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox_SR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox_HS, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox_NS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox_Bluetooth, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox_EW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBox_GPS, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBox_EW)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox_GPS))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBox_NS)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox_Bluetooth))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBox_AC)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox_AB))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jCheckBox_SR)
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox_HS)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Class:");

        jComboBox2_Fuel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GAS", "PETROL" }));

        jComboBox_brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_brandActionPerformed(evt);
            }
        });

        jComboBox_color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "White", "Black ", "Red ", "Blue", "Yellow", "Grey", "Green", "Brown", "Orange", " " }));

        jSpinner_Passenger.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jButton_Add.setBackground(new java.awt.Color(230, 126, 34));
        jButton_Add.setText("ADD");
        jButton_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AddActionPerformed(evt);
            }
        });

        jButton_Brands_List_.setBackground(new java.awt.Color(230, 126, 34));
        jButton_Brands_List_.setText("Brands_List");
        jButton_Brands_List_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Brands_List_ActionPerformed(evt);
            }
        });

        jButton_Add_Images_.setBackground(new java.awt.Color(230, 126, 34));
        jButton_Add_Images_.setText("Add_car_images");
        jButton_Add_Images_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add_Images_ActionPerformed(evt);
            }
        });

        jRadioButton_Automatic.setText("Automatic");

        jRadioButton_Manual.setText("Manual");

        jButton_Reset.setBackground(new java.awt.Color(230, 126, 34));
        jButton_Reset.setText("RESET");
        jButton_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetActionPerformed(evt);
            }
        });

        jLabel_id.setText("#");

        jSpinner_id.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("ID:");

        jButton_Add1.setBackground(new java.awt.Color(230, 126, 34));
        jButton_Add1.setText("REMOVE");
        jButton_Add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add1ActionPerformed(evt);
            }
        });

        jButton_Add2.setBackground(new java.awt.Color(230, 126, 34));
        jButton_Add2.setText("EDIT");
        jButton_Add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Add2ActionPerformed(evt);
            }
        });

        jButton_Brands_List_1.setBackground(new java.awt.Color(230, 126, 34));
        jButton_Brands_List_1.setText("Car_List");
        jButton_Brands_List_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Brands_List_1ActionPerformed(evt);
            }
        });

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpinner_id)
                    .addComponent(jComboBox_color, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_Model)
                    .addComponent(jComboBox2_Fuel, 0, 184, Short.MAX_VALUE)
                    .addComponent(jComboBox_brand, 0, 184, Short.MAX_VALUE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel_id)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinner_Passenger)
                                    .addComponent(jTextField_Class)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel6))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButton_Automatic)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButton_Manual))
                                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jButton2)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Add2, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                            .addComponent(jButton_Add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(130, 130, 130)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Add1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Brands_List_1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton_Brands_List_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton_Add_Images_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinner_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jButton2))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField_Class, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jSpinner_Passenger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jRadioButton_Automatic)
                            .addComponent(jRadioButton_Manual)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_id))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_Model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jComboBox2_Fuel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jComboBox_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_Add)
                                    .addComponent(jButton_Add1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton_Add_Images_)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Brands_List_)
                            .addComponent(jButton_Reset)
                            .addComponent(jButton_Add2))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_Brands_List_1)
                        .addGap(44, 44, 44))))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox_ACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_ACActionPerformed

    private void jCheckBox_ABActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_ABActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_ABActionPerformed

    private void jCheckBox_HSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_HSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_HSActionPerformed

    private void jCheckBox_SRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_SRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_SRActionPerformed

    private void jCheckBox_BluetoothActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_BluetoothActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_BluetoothActionPerformed

    private void jCheckBox_NSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_NSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_NSActionPerformed

    private void jCheckBox_GPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_GPSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_GPSActionPerformed

    private void jCheckBox_EWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox_EWActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox_EWActionPerformed

    private void jButton_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AddActionPerformed
        // add a new car
        //car info
        int id = Integer.valueOf( jLabel_id.getText());
        int brand = Integer.valueOf(jLabel_id.getText());
        String model = jTextField_Model.getText();
        String fuel = jComboBox2_Fuel.getSelectedItem().toString();
        String color = jComboBox_color.getSelectedItem().toString();
        String _class_ = jTextField_Class.getText();
        int passengers = (int) jSpinner_Passenger.getValue();
        String gearbox = "automatic";
        int price = (int) jSpinner1.getValue();
        //car features
        String air_cond = "no";
        String airbags = "no";
        String sunroof = "no";
        String heated_seats = "no";
        String nav_sys = "no";
        String bluetooth = "no";
        String elec_win = "no";
        String gps = "no";
        
        if(jRadioButton_Manual.isSelected())
        {
            gearbox="manual";
        }
        if(jCheckBox_AC.isSelected())
        {
            air_cond="yes";
        }
        if(jCheckBox_AB.isSelected())
        {
            airbags="yes";
        }
        if(jCheckBox_SR.isSelected())
        {
            sunroof="yes";
        }
        if(jCheckBox_HS.isSelected())
        {
            heated_seats="yes";
        }
        if(jCheckBox_NS.isSelected())
        {
            nav_sys="yes";
        }
        if(jCheckBox_Bluetooth.isSelected())
        {
            bluetooth="yes";
        }
        if(jCheckBox_EW.isSelected())
        {
            elec_win="yes";
        }
        if(jCheckBox_GPS.isSelected())
        {
            gps="yes";
        }
        
        cr.addCar(id,brand,  model, fuel, color, _class_, passengers, gearbox, price, air_cond, airbags, sunroof, heated_seats, nav_sys, bluetooth, elec_win, gps);
    }//GEN-LAST:event_jButton_AddActionPerformed

    private void jButton_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetActionPerformed
        // clear all fields
        jTextField_Class.setText("");
        jTextField_Model.setText("");
        jSpinner1.setValue(0);
        jSpinner_Passenger.setValue(0);
       jSpinner_id.setValue(0);
        jComboBox2_Fuel.setSelectedIndex(0);
        jComboBox_color.setSelectedIndex(0);
        jComboBox_brand.setSelectedIndex(0);
        jRadioButton_Automatic.setSelected(false);
        jRadioButton_Manual.setSelected(false);
        
        jCheckBox_AC.setSelected(false);
        jCheckBox_AB.setSelected(false);
        jCheckBox_SR.setSelected(false);
        jCheckBox_HS.setSelected(false);
        jCheckBox_NS.setSelected(false);
        jCheckBox_Bluetooth.setSelected(false);
        jCheckBox_EW.setSelected(false);
        jCheckBox_GPS.setSelected(false);
        
       
    }//GEN-LAST:event_jButton_ResetActionPerformed

    private void jComboBox_brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_brandActionPerformed
        // getting the selected brand id
        int brand=0;
        for(Map.Entry<Integer,String> entry:map.entrySet())
        {
            if(entry.getValue().equals(jComboBox_brand.getSelectedItem().toString()))
            {
                brand = entry.getKey();
            }
        }
        jLabel_id.setText(String.valueOf(brand));
    }//GEN-LAST:event_jComboBox_brandActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        menu me_nu = new menu();
        me_nu.setVisible(true);
                             
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_Add_Images_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add_Images_ActionPerformed
        // opens add car images tab
        setVisible(false);
        Form_CarImages cr = new Form_CarImages();
        cr.setVisible(true);
    }//GEN-LAST:event_jButton_Add_Images_ActionPerformed

    private void jButton_Brands_List_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Brands_List_ActionPerformed
        // open  brandslist tab
        setVisible(false);
        Form_BrandsList bl = new Form_BrandsList();
        bl.setVisible(true);
    }//GEN-LAST:event_jButton_Brands_List_ActionPerformed

    private void jButton_Add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add1ActionPerformed
        // remove
       int _id = (int) jSpinner_id.getValue();
           int  confirm = JOptionPane.showConfirmDialog(null, "Are You Sure You Want To Delete This Brand?" );
        //int YES_NO_OPTION = JOptionPane.YES_NO_OPTION;
           if(confirm==JOptionPane.YES_OPTION)
           {
           //brand_cls brand = new brand_cls();
            cr.removeCar(_id);
           }
    }//GEN-LAST:event_jButton_Add1ActionPerformed

    private void jButton_Add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Add2ActionPerformed
        // edit
         int id = (int) jSpinner_id.getValue();
        int brand =  Integer.valueOf(jLabel_id.getText());
        String model = jTextField_Model.getText();
        String fuel = jComboBox2_Fuel.getSelectedItem().toString();
        String color = jComboBox_color.getSelectedItem().toString();
        String _class_ = jTextField_Class.getText();
        int passengers = (int) jSpinner_Passenger.getValue();
        String gearbox = "automatic";
        int price = (int) jSpinner1.getValue();
        //jComboBox_brand.getSelectedItem();
        //car features
        String air_cond = "no";
        String airbags = "no";
        String sunroof = "no";
        String heated_seats = "no";
        String nav_sys = "no";
        String bluetooth = "no";
        String elec_win = "no";
        String gps = "no";
        
        if(jRadioButton_Manual.isSelected())
        {
            gearbox="manual";
        }
        if(jCheckBox_AC.isSelected())
        {
            air_cond="yes";
        }
        if(jCheckBox_AB.isSelected())
        {
            airbags="yes";
        }
        if(jCheckBox_SR.isSelected())
        {
            sunroof="yes";
        }
        if(jCheckBox_HS.isSelected())
        {
            heated_seats="yes";
        }
        if(jCheckBox_NS.isSelected())
        {
            nav_sys="yes";
        }
        if(jCheckBox_Bluetooth.isSelected())
        {
            bluetooth="yes";
        }
        if(jCheckBox_EW.isSelected())
        {
            elec_win="yes";
        }
        if(jCheckBox_GPS.isSelected())
        {
            gps="yes";
        }
        
        cr.editCar(id, brand,  model, fuel, color, _class_, passengers, gearbox, price, air_cond, airbags, sunroof, heated_seats, nav_sys, bluetooth, elec_win, gps);
    
    }//GEN-LAST:event_jButton_Add2ActionPerformed

    private void jButton_Brands_List_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Brands_List_1ActionPerformed
        // display car list
         setVisible(false);
        Form_CarList cl = new Form_CarList();
        cl.setVisible(true);
    }//GEN-LAST:event_jButton_Brands_List_1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // search by id
        int car_id = (int) jSpinner_id.getValue();
        Car new_car = cr.getCarById(car_id);
        //reset all fields
        jButton_ResetActionPerformed(null);
        if(new_car == null)
        {
            JOptionPane.showMessageDialog(null," Car Not Available "," Invalid info ",2);
        }
        else
        {
        jTextField_Class.setText(new_car.getClass_());
        jTextField_Model.setText(new_car.getModel());
       
        jSpinner1.setValue(new_car.getPrice());
        jSpinner_Passenger.setValue(new_car.getPassengers());
        jSpinner_id.setValue(0);
        
        
        jComboBox2_Fuel.setSelectedItem(new_car.getFuel());
        jComboBox_color.setSelectedItem(new_car.getColor());
        jComboBox_brand.setSelectedItem(map.get(new_car.getBrand()));
         
        jLabel_id.setText(String.valueOf(new_car.getBrand()));
        
       
         if(new_car.getGearbox().equals("manual"))
        {
            jRadioButton_Manual.setSelected(true);
        }
        if(new_car.getGearbox().equals("yes"))
        {
            jCheckBox_AC.setSelected(true);
        }
        if(new_car.getAirbag().equals("yes"))
        {
            jCheckBox_AB.setSelected(true);
        }
        if(new_car.getSunroof().equals("yes"))
        {
            jCheckBox_SR.setSelected(true);
        }
        if(new_car.getHeated_seats().equals("yes"))
        {
            jCheckBox_HS.setSelected(true);
        }
        if(new_car.getNav_system().equals("yes"))
        {
            jCheckBox_NS.setSelected(true);
        }
        if(new_car.getBluetooth().equals("yes"))
        {
            jCheckBox_Bluetooth.setSelected(true);
        }
        if(new_car.getElec_window().equals("yes"))
        {
            jCheckBox_EW.setSelected(true);
        }
        
        if(new_car.getGps().equals("yes"))
        {
            jCheckBox_GPS.setSelected(true);
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Car().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton_Add;
    private javax.swing.JButton jButton_Add1;
    private javax.swing.JButton jButton_Add2;
    private javax.swing.JButton jButton_Add_Images_;
    private javax.swing.JButton jButton_Brands_List_;
    private javax.swing.JButton jButton_Brands_List_1;
    private javax.swing.JButton jButton_Reset;
    private javax.swing.JCheckBox jCheckBox_AB;
    private javax.swing.JCheckBox jCheckBox_AC;
    private javax.swing.JCheckBox jCheckBox_Bluetooth;
    private javax.swing.JCheckBox jCheckBox_EW;
    private javax.swing.JCheckBox jCheckBox_GPS;
    private javax.swing.JCheckBox jCheckBox_HS;
    private javax.swing.JCheckBox jCheckBox_NS;
    private javax.swing.JCheckBox jCheckBox_SR;
    private javax.swing.JComboBox<String> jComboBox2_Fuel;
    private javax.swing.JComboBox<String> jComboBox_brand;
    private javax.swing.JComboBox<String> jComboBox_color;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_id;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton_Automatic;
    private javax.swing.JRadioButton jRadioButton_Manual;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner_Passenger;
    private javax.swing.JSpinner jSpinner_id;
    private javax.swing.JTextField jTextField_Class;
    private javax.swing.JTextField jTextField_Model;
    // End of variables declaration//GEN-END:variables
}
